name: CI

on: [push]

jobs:
  testing:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ windows ]
        ruby: [ 2.4, 2.5.0, 2.5.1, 2.5.3, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.6.0, 2.6, 2.7 ]
        include:
          - { os: windows, ruby: mingw }
          - { os: windows, ruby: mswin }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby Install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: binding issue
        run: ruby binding-local-variable.rb
